// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tpjg.Nanovms
{
    /// <summary>
    /// A NanoVMs package image resource for building unikernel images from packages
    /// </summary>
    [NanovmsResourceType("nanovms:index:PackageImage")]
    public partial class PackageImage : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The target architecture of the built image
        /// </summary>
        [Output("architecture")]
        public Output<string> Architecture { get; private set; } = null!;

        /// <summary>
        /// The configuration of the built image as a JSON encoded string
        /// </summary>
        [Output("config")]
        public Output<string> Config { get; private set; } = null!;

        /// <summary>
        /// The name of the built image
        /// </summary>
        [Output("imageName")]
        public Output<string> ImageName { get; private set; } = null!;

        /// <summary>
        /// The path to the built image
        /// </summary>
        [Output("imagePath")]
        public Output<string> ImagePath { get; private set; } = null!;

        /// <summary>
        /// The name of the package used
        /// </summary>
        [Output("packageName")]
        public Output<string> PackageName { get; private set; } = null!;

        /// <summary>
        /// The cloud provider of the built image
        /// </summary>
        [Output("provider")]
        public Output<string> Provider { get; private set; } = null!;

        /// <summary>
        /// If the latest kernel should be used, download it if necessary
        /// </summary>
        [Output("useLatestKernel")]
        public Output<bool> UseLatestKernel { get; private set; } = null!;


        /// <summary>
        /// Create a PackageImage resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PackageImage(string name, PackageImageArgs args, CustomResourceOptions? options = null)
            : base("nanovms:index:PackageImage", name, args ?? new PackageImageArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PackageImage(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("nanovms:index:PackageImage", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PackageImage resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PackageImage Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PackageImage(name, id, options);
        }
    }

    public sealed class PackageImageArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The target architecture (amd64 or arm64). If not specified, uses the current system architecture
        /// </summary>
        [Input("architecture")]
        public Input<string>? Architecture { get; set; }

        /// <summary>
        /// The configuration as a JSON encoded string
        /// </summary>
        [Input("config")]
        public Input<string>? Config { get; set; }

        /// <summary>
        /// If an already existing image should be deleted if it exists
        /// </summary>
        [Input("force")]
        public Input<bool>? Force { get; set; }

        /// <summary>
        /// The name of the image
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The name of the package to use (e.g., 'node_v18.7.0')
        /// </summary>
        [Input("packageName", required: true)]
        public Input<string> PackageName { get; set; } = null!;

        /// <summary>
        /// The target cloud provider (e.g., onprem, gcp, aws, azure, oracle, openstack, vsphere, upcloud, do, linode, vultr)
        /// </summary>
        [Input("provider", required: true)]
        public Input<string> Provider { get; set; } = null!;

        /// <summary>
        /// If the latest kernel should be used, download it if necessary
        /// </summary>
        [Input("useLatestKernel")]
        public Input<bool>? UseLatestKernel { get; set; }

        public PackageImageArgs()
        {
        }
        public static new PackageImageArgs Empty => new PackageImageArgs();
    }
}
