# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .image import *
from .instance import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "pulumi-nanovms",
  "mod": "index",
  "fqn": "tpjg_pulumi_nanovms",
  "classes": {
   "pulumi-nanovms:index:Image": "Image",
   "pulumi-nanovms:index:Instance": "Instance"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "pulumi-nanovms",
  "token": "pulumi:providers:pulumi-nanovms",
  "fqn": "tpjg_pulumi_nanovms",
  "class": "Provider"
 }
]
"""
)
