// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.tpjg.puluminanovms;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.tpjg.puluminanovms.InstanceArgs;
import com.tpjg.puluminanovms.Utilities;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * A NanoVMs resource for deploying unikernel images
 * 
 */
@ResourceType(type="pulumi-nanovms:index:Instance")
public class Instance extends com.pulumi.resources.CustomResource {
    /**
     * The configuration for the instance
     * 
     */
    @Export(name="config", refs={String.class}, tree="[0]")
    private Output<String> config;

    /**
     * @return The configuration for the instance
     * 
     */
    public Output<String> config() {
        return this.config;
    }
    /**
     * The name of the image deployed
     * 
     */
    @Export(name="image", refs={String.class}, tree="[0]")
    private Output<String> image;

    /**
     * @return The name of the image deployed
     * 
     */
    public Output<String> image() {
        return this.image;
    }
    /**
     * The unique identifier for the instance
     * 
     */
    @Export(name="instanceID", refs={String.class}, tree="[0]")
    private Output<String> instanceID;

    /**
     * @return The unique identifier for the instance
     * 
     */
    public Output<String> instanceID() {
        return this.instanceID;
    }
    /**
     * The provider instance ID
     * 
     */
    @Export(name="pid", refs={String.class}, tree="[0]")
    private Output<String> pid;

    /**
     * @return The provider instance ID
     * 
     */
    public Output<String> pid() {
        return this.pid;
    }
    /**
     * The private IP addresses of the instance
     * 
     */
    @Export(name="private_ips", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> private_ips;

    /**
     * @return The private IP addresses of the instance
     * 
     */
    public Output<List<String>> private_ips() {
        return this.private_ips;
    }
    /**
     * The provider (type) for the instance
     * 
     */
    @Export(name="provider", refs={String.class}, tree="[0]")
    private Output<String> provider;

    /**
     * @return The provider (type) for the instance
     * 
     */
    public Output<String> provider() {
        return this.provider;
    }
    /**
     * The public IP addresses of the instance
     * 
     */
    @Export(name="public_ips", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> public_ips;

    /**
     * @return The public IP addresses of the instance
     * 
     */
    public Output<List<String>> public_ips() {
        return this.public_ips;
    }
    /**
     * The status of the instance
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return The status of the instance
     * 
     */
    public Output<String> status() {
        return this.status;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Instance(java.lang.String name) {
        this(name, InstanceArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Instance(java.lang.String name, InstanceArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Instance(java.lang.String name, InstanceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumi-nanovms:index:Instance", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Instance(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumi-nanovms:index:Instance", name, null, makeResourceOptions(options, id), false);
    }

    private static InstanceArgs makeArgs(InstanceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? InstanceArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Instance get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Instance(name, id, options);
    }
}
