// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.tpjg.puluminanovms;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.tpjg.puluminanovms.PackageImageArgs;
import com.tpjg.puluminanovms.Utilities;
import java.lang.Boolean;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * A NanoVMs package image resource for building unikernel images from packages
 * 
 */
@ResourceType(type="pulumi-nanovms:index:PackageImage")
public class PackageImage extends com.pulumi.resources.CustomResource {
    /**
     * The configuration of the built image as a JSON encoded string
     * 
     */
    @Export(name="config", refs={String.class}, tree="[0]")
    private Output<String> config;

    /**
     * @return The configuration of the built image as a JSON encoded string
     * 
     */
    public Output<String> config() {
        return this.config;
    }
    /**
     * The name of the built image
     * 
     */
    @Export(name="imageName", refs={String.class}, tree="[0]")
    private Output<String> imageName;

    /**
     * @return The name of the built image
     * 
     */
    public Output<String> imageName() {
        return this.imageName;
    }
    /**
     * The path to the built image
     * 
     */
    @Export(name="imagePath", refs={String.class}, tree="[0]")
    private Output<String> imagePath;

    /**
     * @return The path to the built image
     * 
     */
    public Output<String> imagePath() {
        return this.imagePath;
    }
    /**
     * The name of the package used
     * 
     */
    @Export(name="packageName", refs={String.class}, tree="[0]")
    private Output<String> packageName;

    /**
     * @return The name of the package used
     * 
     */
    public Output<String> packageName() {
        return this.packageName;
    }
    /**
     * The cloud provider of the built image
     * 
     */
    @Export(name="provider", refs={String.class}, tree="[0]")
    private Output<String> provider;

    /**
     * @return The cloud provider of the built image
     * 
     */
    public Output<String> provider() {
        return this.provider;
    }
    /**
     * If the latest kernel should be used, download it if necessary
     * 
     */
    @Export(name="useLatestKernel", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> useLatestKernel;

    /**
     * @return If the latest kernel should be used, download it if necessary
     * 
     */
    public Output<Boolean> useLatestKernel() {
        return this.useLatestKernel;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public PackageImage(java.lang.String name) {
        this(name, PackageImageArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public PackageImage(java.lang.String name, PackageImageArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public PackageImage(java.lang.String name, PackageImageArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumi-nanovms:index:PackageImage", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private PackageImage(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumi-nanovms:index:PackageImage", name, null, makeResourceOptions(options, id), false);
    }

    private static PackageImageArgs makeArgs(PackageImageArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? PackageImageArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static PackageImage get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new PackageImage(name, id, options);
    }
}
